// frontend/src/components/VRightSidebar.tsx
import { useAnimateForm, useStore } from "../store"
import { Form, Input, InputNumber, Radio, Select, Tabs } from "antd"

import React, { useState } from "react"

interface FieldData {
  name: string | number | (string | number)[]
  value?: any
  touched?: boolean
  validating?: boolean
  errors?: string[]
}

interface CustomizedFormProps {
  onChange: (fields: FieldData[]) => void
  fields: FieldData[]
}

const CustomizedForm: React.FC<CustomizedFormProps> = ({ onChange, fields }) => {
  const { performances, aspect_ratios } = useStore()

  return (
    <Form
      layout="vertical"
      className="text-left"
      name="global_state"
      fields={fields}
      onFieldsChange={(_, allFields) => {
        onChange(allFields)
      }}
    >
      <Form.Item label="Performance" name="performance" tooltip="Use LCM for extreme speed">
        <Radio.Group>
          {performances.map((p) => (
            <Radio key={p} value={p}>
              {p}
            </Radio>
          ))}
        </Radio.Group>
      </Form.Item>
      <Form.Item label="Aspect Radios" name="aspect_ratio">
        <Radio.Group>
          {aspect_ratios.map((p) => (
            <Radio key={p} value={p}>
              {p}
            </Radio>
          ))}
        </Radio.Group>
      </Form.Item>
      <Form.Item label="Head Prompt" name="head prompt">
        <Input />
      </Form.Item>
      <Form.Item label="Tail Prompt" name="tail prompt">
        <Input />
      </Form.Item>
      <Form.Item label="Negative Prompt" name="negative prompt">
        <Input />
      </Form.Item>
      <Form.Item label="Seed" name="seed">
        <InputNumber />
      </Form.Item>
      <div className="flex space-x-5">
        <Form.Item label="Duration(s)" name="duration">
          <InputNumber />
        </Form.Item>
        <Form.Item label="FPS" name="fps">
          <InputNumber />
        </Form.Item>
      </div>
    </Form>
  )
}

export function VRightSidebar() {
  const { performances, motions, motion_loras, checkpoints, aspect_ratios, loras: loraOps } = useStore()
  const { loras, performance, aspect_ratio, setSettingsFormFields, settingsFormFields } = useAnimateForm()

  return (
    <div className="h-[800px] w-[300px] border-b-[1px] border-r-[1px] border-gray-200 px-5 py-2">
      <Tabs
        animated
        defaultActiveKey="1"
        className="h-full w-[260px]"
        items={[
          {
            key: "1",
            label: "Setting",
            children: (
              <CustomizedForm
                fields={settingsFormFields}
                onChange={(newFields) => {
                  setSettingsFormFields(newFields)
                }}
              />
            ),
          },
          {
            key: "2",
            label: "Models",
            children: (
              <Form
                layout="vertical"
                initialValues={{
                  checkpoint: "checkpoint",
                  motion: "motion",
                  motion_lora: "motion_lora",
                  loras: [
                    ["lora1", 1],
                    ["lora2", 1],
                    ["lora3", 1],
                    ["lora4", 1],
                    ["lora5", 1],
                  ],
                }}
                className="text-left"
              >
                <Form.Item label="Checkpoint" name="checkpoint">
                  <Select>
                    {checkpoints.map((p) => (
                      <Select.Option key={p.name} value={p.name}>
                        {p.name}
                      </Select.Option>
                    ))}
                  </Select>
                </Form.Item>
                {loras.map((lora, idx) => {
                  return (
                    <div className="flex space-x-5">
                      <Form.Item label={`Lora ${idx + 1}`} key={idx} name={["loras", idx, 0]}>
                        <Select
                          style={{
                            width: "150px",
                          }}
                        >
                          {loraOps.map((p) => (
                            <Select.Option key={p.name} value={p.name}>
                              {p.name}
                            </Select.Option>
                          ))}
                        </Select>
                      </Form.Item>
                      <Form.Item label="weight" name={["loras", idx, 1]}>
                        <InputNumber />
                      </Form.Item>
                    </div>
                  )
                })}
                <Form.Item label="Motion" name="motion">
                  <Select>
                    {motions.map((p) => (
                      <Select.Option value={p.name}>{p.name}</Select.Option>
                    ))}
                  </Select>
                </Form.Item>
                <Form.Item label="Motion LoRA" name="motion_lora">
                  <Select>
                    {motion_loras.map((p) => (
                      <Select.Option value={p.name}>{p.name}</Select.Option>
                    ))}
                  </Select>
                </Form.Item>
              </Form>
            ),
          },
          {
            key: "3",
            label: "Advanced",
            children: "Content of Tab Pane 3",
          },
        ]}
      ></Tabs>
    </div>
  )
}

// frontend/src/components/VRightSidebar.vue
<script setup lang="ts">

const {
  options,
} = useStore()
const { form } = useAnimateForm()
console.log(options.value)

const unflatten = (arr: any[]) => {
  return arr.map((x) => {
    return {
      label: x,
      value: x,
    }
  })
}

const unflattenCheckpoint = (arr: any[]) => {
  return arr.map((x) => {
    return {
      label: x.name,
      value: x.name,
    }
  })
}
const perfOptions = unflatten(performances)

const aspectRadioOptions = unflatten(aspect_ratios)

const checkpointOptions = unflattenCheckpoint(options.value.checkpoints)

const motionOptions = unflattenCheckpoint(options.value.motions)
const motionLorasOptions = unflattenCheckpoint(options.value.motion_loras)
const lorasOptions = unflattenCheckpoint(options.value.loras)
console.log(perfOptions, checkpointOptions, lorasOptions, toRaw(options.value))

const advanced = ref({
  cfg: 1,
})
const activeKey = ref("1")

</script>
<template>
  <div class="w-[500px] h-[800px] border-gray-200 border-r-[1px] border-b-[1px] py-2 px-5">
    <a-tabs v-model:activeKey="activeKey">
      <a-tab-pane key="1" tab="Setting">
        <AForm
            layout="vertical"
        >
          <a-form-item
              label="Performance"
          >
            <a-radio-group
                v-model:value="form.performance"
            >
              <a-radio
                  v-for="_ in perfOptions"
                  :key="_.value"
                  :value="_.value"
                  :label="_.label"
              > {{ _.value }}
              </a-radio>
            </a-radio-group>
          </a-form-item>
          <a-form-item
              label="Aspect Radios"
          >
            <a-radio-group
                v-model:value="form.aspect_ratio"
            >
              <a-radio
                  v-for="ar in aspectRadioOptions"
                  :key="ar.value"
                  class="font-mono"
                  :value="ar.value"
                  :label="ar.label"
              >{{ ar.value }}
              </a-radio>
            </a-radio-group>
          </a-form-item>
          <a-form-item
              label="Head Prompt"
          >
            <a-input :value="form.head_prompt"/>
          </a-form-item>
          <a-form-item
              label="Tail Prompt"
          >
            <a-textarea
                v-model:value="form.tail_prompt"
            />
          </a-form-item>
          <a-form-item
              label="Negative Prompt"
          >
            <a-textarea
                v-model:value="form.negative_prompt"
            />
          </a-form-item>
          <a-form-item
              label="Seed"
          >
            <a-input-number v-model:value="form.seed" step="1"/>
          </a-form-item>
          <div class="flex space-x-5">
            <a-form-item
                label="Duration(s)"
            >
              <a-input-number
                  step="1"
                  min="1"
                  max="600"
                  v-model:value="form.duration"
              />
            </a-form-item>
            <a-form-item
                label="FPS"
            >
              <a-input-number
                  step="1"
                  min="4"
                  max="16"
                  v-model:value="form.fps"
              />
            </a-form-item>
          </div>
        </AForm>
      </a-tab-pane>
      <a-tab-pane key="2" tab="Model">
        <a-form
            layout="vertical"
        >
          <a-form-item
              label="Checkpoint"
          >
            <a-select
                v-model:value="form.checkpoint"
                :options="checkpointOptions"
            />
          </a-form-item>
        </a-form>
        <a-form
            layout="vertical"
        >
          <a-form-item
              v-for="(song, idx) in form.loras"
              class="form-item-no-feedback"
              :label="`LoRA ${idx + 1}`"
          >
            <div class="flex">
              <a-select
                  v-model:value="song.name"
                  size="small"
                  class="w-[150px] min-w-[150px]"
                  :options="lorasOptions"
              />
              <a-input-number
                  v-model:value="song.weight"
                  size="small"
                  min="0"
                  max="2"
                  step="0.1"
                  class="ml-2"
              />
            </div>
          </a-form-item>
          <a-form
              class="pt-5"
              layout="vertical"
          >
            <a-form-item
                label="Motion"
            >
              <a-select
                  v-model:value="form.motion"
                  :options="motionOptions"
              />
            </a-form-item>
            <a-form-item
                label="Motion LoRAs"
            >
              <a-select
                  v-model:value="form.motion_lora"
                  :options="motionLorasOptions"
              />
            </a-form-item>
          </a-form>
        </a-form>
      </a-tab-pane>
      <a-tab-pane key="3" tab="Advanced">
        <a-form-item
            label="cfg"
            size="small"
        >
          <a-slider
              v-model:value="advanced.cfg"
          />
        </a-form-item>
      </a-tab-pane>
    </a-tabs>
  </div>
</template>

<style>
.form-item-no-feedback .n-form-item-feedback-wrapper {
  display: none;
}
</style>
